### PR TITLE
Update to v3.19.1 from upstream

### PR DESCRIPTION
**Pull request by rplopes**
Update this fork to the latest version of the upstream project.

### CODE REVIEW

**Comment by ruimarinho** [comment]
Suggestion: reset hard to upstream/master and cherry-pick the default fix commit please.

**Comment by rplopes** [comment]
@ruimarinho so do we want to discard the other change? And just keep 0fcabcb062eec95fc82ea4bd15485004457f1c07?

**Comment by rplopes** [comment]
Main changes from 3.6.0 to 3.19.1:
- Define field dependencies for VIRTUAL types that are automatically pulled into `attributes`
- beforeRestore/afterRestore hooks
- Map raw fields back to attributes names when using `mapToModel` or `returning`
- `skip` now supports filtering out model validators
- Expose Association constructor as `Sequelize.Association`
- beforeSync/afterSync/beforeBulkSync/afterBulksync hooks
- Added `include` and `exclude` to `options.attributes`
- `.previous` now returns and object of previous values when called without `key`. This brings the API in line with `.changed`
- PostgreSQL tsrange (Range of timestamp without time zone) data type support
- hasOne scope support
- Support silent: true in bulk update
- `retry` object now part of global settings and can be overridden per call. The default is 5 retries with a backoff function. `retry` object can be passed to options with max: 0 to turn off this behavior.
- Geography support for postgres

**Comment by ruimarinho** [comment]
Closing in favour of https://github.com/seegno-forks/sequelize/pull/5 which builds on top of this.

**Pull request closed without merging**
